### ISSUE TITLE
Do not allow passing wrong entity state kind

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/core-java#1548]
Now it is possible to declare an entity class with an entity state of a wrong kind. For example, it is possible to create a `Projection` with a message implementing `EntityState` which has the following option declaration:

```proto
option (.entity) = { kind: PROCESS_MANAGER visibility: QUERY };
```

Although, it does not do any harm, it's obviously a programming error. This is not what the developer intended. Moreover, keeping such errors unnoticed prevents us from introducing specific interfaces for entity states for projections, process managers, and aggregates.

### Suggested actions
- [ ] 1. Check the option of an entity state on run-time when creating an `EntityClass`.
- [ ] 2. Using the runtime checks above, eliminate such errors in the existing code.
- [ ] 3. Introduce `ProjectionState`, `ProcessManagerState`, and `AggregateState` interfaces which implement `EntityState`.
- [ ] 4. Update code generation to use new interfaces from the item 3 above.

**Comment by armiol** [comment]
@alexander-yevsyukov I would go with pp. 3 and 4. 

Points no.1 and no.2 do not lead to a compilation failure, which we ideally want. And they may be both expensive and restrictive in terms of GraalVM compatibility.
