### ISSUE TITLE
Release v.1.0 checklist

### ISSUE THREAD

**Issue by armiol** [SpineEventEngine/core-java#464]
The following actions must be completed before the v1.0 is released.

Update `README.md` in **core-java**:
- [ ] links follow to proper destination pages;
- [ ] dependency list reflects the up-to-date state of the project.
  
Review Javadocs:
- [ ] Javadoc sections contain no grammar issues;
- [ ] rendered HTML files are readable and do not require any additional formatting.

Review the dependencies:
- [ ] the project has no dependencies to the same artifact in different versions.

**Comment by alexander-yevsyukov** [comment]
I think we need to bring our core dependencies as repackaged, similarly to [how Beam does this](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/pom.xml).

See the section: 
```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <id>bundle-and-repackage</id>
            <phase>none</phase>
          </execution>
        </executions>
      </plugin>
```
... and the internal structure of the Beam jars. For example, `org.apache.beam.sdk.repackaged`.

**Comment by alexander-yevsyukov** [comment]
Here's a candidate for [shadowing in Gradle](https://plugins.gradle.org/plugin/com.github.johnrengelman.plugin-shadow).

**Comment by armiol** [comment]
Let's think of publishing two versions of Spine:

* `...-no-dep` version, with the dependencies repackaged;
* current version, built upon the declarative dependency mechanism.

**Comment by alexander-yevsyukov** [comment]
@armiol, here's the plugin for checking usage of Guava Beta API:

https://github.com/google/guava-beta-checker

Let's discuss our actions on this topic.
